// patch.h generator
// leecher@dose.0wnz.at 05/2023
//
#include <stdio.h>
#include <errno.h>

int main(int argc, char **argv)
{
    FILE *fp;
    unsigned char buf[28];
    int i, j;
    
    if (argc<2)
    {
        fprintf(stderr, "Usage: %s <SYNTH.PAT file>\n\n");
        return -1;
    }
    if (!(fp = fopen(argv[1], "rb")))
    {
        perror("Cannot open .PAT file");
        return -1;
    }
    fseek(fp, 0x14, SEEK_SET);
    printf("//\n" \
"//   Copyright (c) 1996-2000 Microsoft Corporation.  All rights reserved.\n" \
"//\n" \
"// ==============================================\n" \
"// This file is generated programmatically from\n" \
"// a RIFF file synth.pat. \n" \
"\n" \
"// Please do not edit this file.\n" \
"// ==============================================\n" \
"\n" \
"patchStruct glpPatch[] = \n" \
"{\n" \
"    ");
    for (i=1; fread(buf, sizeof(buf), 1, fp); i++)
    {
		if (i>1) printf (",");
        printf ("{   //  %d",i);
        if (i%10 == 1) printf("st");
        else if (i%10 == 2) printf ("nd");
        else if (i%10 == 3) printf ("rd");
        else printf ("%th");
        printf (" patch struct\n" \
        
            "        ");
        for (j=0; j<sizeof(buf); j++)
        {
            if (j) printf (",");
            printf ("0x%02x", buf[j]);
        }
        printf ("\n    }");
    }
    printf ("\n};\n");
    fclose(fp);
    return 0;
}
